version: "2"
services:
  mysql:
    image: registry.cn-qingdao.aliyuncs.com/dzcyw/mysql:5.7
    ports:
      - 3307:3307
    volumes:
      - ~/cloudShopping-deploy/mysql/data:/var/lib/mysql
      - ~/cloudShopping-deploy/mysql/log:/var/log/mysql
      - ~/cloudShopping-deploy/mysql/conf:/etc/mysql/mysql.conf.d/
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_DATABASE: cloudShopping_db


  #cloudShopping:
    #image: ccr.ccs.tencentyun.com/antiratech/cloudshopping:1.0.1
    #volumes:
        #- ~/cloudShopping-deploy/cloudShopping/logs:/logs
        #- ~/cloudShopping-deploy/cloudShopping/waf_default:/waf_default
        #- /etc/localtime:/etc/localtime
    #ports:
        #- 5002:5002



